In [3]:
import numpy as np

#1. an array of int b/w -10 and 10
arr=np.arange(-10,10)
arr

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,
         3,   4,   5,   6,   7,   8,   9])

In [14]:
#2 Run the following code to create a NumPy array D
#D = np.array(range(18)) + 3
#(a) Extract every other value from array D starting from the 2nd value through the 10th value. Store the result in a variable called x.
#(b) Extract every other value from array D starting from the 10th value through the 2nd value. Store the result in a variable called y.
#(c) Create a variable z that contains all of the values in D in reverse order.

D=np.array(range(18))+3
x=D[1:9:2]
y=D[9:0:-2]
z=D[::-1]
print(x)
print(y)
print(z)

[ 4  6  8 10]
[12 10  8  6  4]
[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3]


In [ ]:
#3 How are NumPy Arrays better than Lists in Python?  

ans.Numpy arrays are capable of doing computations  faster than lists.
Many built-in functions in numpy library make it easier to compute faster,save time 
with less lines of code which makes the code easy to read.

In [ ]:
#4 Explain the data types supported by Numpy. 

ans.ndarray i.e n-dimensional array.